apiVersion: v2
name: open-zaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 0.8.3
# https://github.com/open-zaak/open-zaak/tags
appVersion: 1.12.5

dependencies:
  - name: postgresql
    version: ~15.5.5
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~19.5.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
